### ISSUE TITLE
VanJS needs help!

### ISSUE THREAD

**Issue by Qard** [cambiecollective/cambiecollective.github.io#21]
@apike is looking for people to help with keeping VanJS running. I’m hoping to arrange a meeting at some point to figure out what we can do to help. If anyone is interested, leave a comment and we can try to arrange a meeting time that will work for everyone.

**Comment by keywordnew** [comment]
Count me in!

**Comment by apike** [comment]
Hi friends! I've been more and more focused on managing teams and doing mobile app development, so I'm looking for one or two folks acquainted with meetups and JavaScript to pick up more of the speaker wrangling and logistics for VanJS. Shall we do a Doodle poll to pick a date to chat about this for those who are interested?

**Comment by daffl** [comment]
I'd be down as well.

**Comment by Qard** [comment]
I'll be away or busy all of next week, so perhaps we can arrange a time for the week after, when things have settled down after Node+JS Interactive and the Node.js Collaborator Summit?

**Comment by daffl** [comment]
I'd like to help but will be out of town after the conference until the 21st. Be happy to join after that.

**Comment by apike** [comment]
Okay cool, here's a Doodle link to see what days work: https://doodle.com/poll/knxeqh8qggbdzzgy

**Comment by apike** [comment]
~It looks like Oct 25 is the first day were we can get 6/7 of the respondents, let's make it then. 🚀~

**Comment by apike** [comment]
Update: it now looks like everybody can do **Nov 1st**, including @shmck, @garbles, and @AkimaLunar who are all awesome and interested in helping with the next generation of VanJS. :tada: I've put in a request for 6pm at Shebeen, which if available would give us a relatively quiet place to eat and discuss.

**Comment by Qard** [comment]
Works for me! 👌

**Comment by keywordnew** [comment]
Awesome, I'm stoked to sync up with all you community-minded folks in November!

**Comment by apike** [comment]
Reservation confirmed for 6pm on the 1st at Shebeen. 👍

**Comment by jagonalez** [comment]
I'd also be interested in helping - @ShMcK and I were discussing this up after a recent ReactVancouver meetup where I was one of the speakers. Do you have room for 1 more?

**Comment by garbles** [comment]
I can no longer make the 1st so I'm happy to roll with whatever y'all decide is the best path forward.

**Comment by blairbodnar** [comment]
Hey gang - I'm also interested in helping! I'll swing by this too tonight if you've got room! 😀

**Comment by apike** [comment]
We have a reso for 7 but if an 8th or 9th drops in I expect they can pull chairs in. 👍

**Comment by apike** [comment]
For our 6pm kickoff today, I wrote some notes as a rough agenda for tonight. I'm not sure how much of this we'll get through, but I think it highlights some of the key things worth looking at for "open sourcing" VanJS. This was inspired by @ShMcK's initial thoughts he shared over email, which he can hopefully share more of tonight and going forward.

## State of VanJS
- Started almost 10 years ago, now 3000 members on Meetup
- We get between 100 and 200 people interested in each event
- Originally happened every 2 months, now more like every 6 months
- Lack of speaker selection and venue coordination bandwidth are the primary reason for the drop in frequency
- Current format is 30 min socialization, one talk of 20-40 minutes, 5-10 min socialization, second talk, then off to a restaurant/bar for post-socialization
- An early goal was quality over quantity. This to us meant good production values, having multiple talks, seeking out-of-town speakers, and avoiding the tendency for meetups to be watered down by marketing or recruiting forces, or struggling with overly ambitious meetup frequencies
- Historically topics have been “intermediate”, in that they don’t go overly in-depth due to time constraints, but try to err on the side of “blowing people’s minds” rather than of risking boring audience members who already know the content
- All elements of the above was motivated by Allen’s personal preferences and feedback from early days, and like all aspects of VanJS are worth revisiting.
- How do you all feel VanJS fits in the community today?
	
## Potential Future Goals
- Strengthen, connect, and educate the JavaScript community in Vancouver
- Empower folks passionate about JS in Vancouver to improve and evolve VanJS for the community’s benefit
- Experiment with how the format and content can improve and grow
- Keep VanJS from dying at the hands of marketing, recruiting, or apathy
- Support newcomers and underrepresented groups in our community, both onstage and off
- Maintain the sense that VanJS events are of good quality and worth folks’ time
- Do these seems like good goals? Are we missing anything critical?

## Organization and Governance
- We need to divide up tasks and responsibilities, without making each responsibility so small that it will tend to get lost in communication overhead.
- Key tasks are:
	- Source speakers and plan talk topics
	- Coordinate and book speakers and talks venue
	- Coordinate and book after-drinks venue
	- Write and publish meetup info
	- Wrangle AV and seating day-of
	- MC day-of
	- Sponsor space
	- Field inquiries from inbound marketing
	- Be responsible for the meetup at a meta level, take and implement feedback
- Allen will write the current recipe for each these tasks, but each event will need a committed person to execute the recipes and improve them over time.
- What would you be interested in helping with, if any of those?
- Is it worth formally designating roles, or should each event have a key Host who then delegates ad hoc?
- We have a few options for coordinating between organizers – is Slack, email, Github, or something else the best primary method?

## Format
- We should explore format variations, but getting a variant of the current format running more frequently seems like a good initial goal. Agreement?
- Events have been booked in the past based on speaker and venue availability. Committing to monthly or every other month has some benefits, but requires a certain minimum organizer bandwidth otherwise quality plummets. Are we down to commit to a recurring schedule?
- Would folks be on board with trying every other month being talks and the alternate months just being a social?
- There are lots of bonus things that would be nice to do but we’ve never had the bandwidth. Once VanJS 2.0 is running smoothly, it’d be nice to look into things like name tags, recording and posting videos, broader social media outreach and marketing, ancillary events, etc.
- Some things VanJS has intentionally not done in the past are workshops, food before events, icebreakers, charging admission, opening the floor for announcements and recruitment messages, and doing single-speaker events. We should re-evaluate these over time as experiments or part of a new format.
- Are there any format changes that should be made a priority?
	
## Talk selection and approach
- VanJS started as a speaker series that was technical enough to bring out intermediate and advanced JS developers. Is that still a good target for content, or should VanJS shift to include more beginner-oriented content?
- VanJS has not done a good enough job on speaker diversity, and should have a specific approach for addressing that.
- The speaker coordinator will need to evolve our guidelines on what makes a good topic, ideal talk length, number of talks, lightning talks, topic variety within and between events, and so on. Allen will post a writeup of the status quo to be iterated or even superseded.
- Any high priorities worth discussing about talk topics or speakers?

## Venues
- VFS Café seems pretty popular for now. Finding and booking great venues is hard, but Allen will write up some tips and tricks. Steamclock is happy to keep sponsoring this for now.
- Irish Heather isn’t a perfect venue but it’s relatively easy to book, quieter than some other places, and lets us rearrange ourselves a bit through the night (this is forbidden at most places, and standing with drinks violates Vancouver liquor law). Allen will write up a list of previously attempted venues with some notes.

## Next Steps
- Set up coordination channel (probably a Slack or Github)
- Pick initial roles
- Pick initial new frequency of meetups
- Allen to post “recipe” for VanJS 1.0
- Add additional folks to roles on Meetup.com
- Schedule first VanJS 2.0 event

**Comment by keywordnew** [comment]
Sooo stoked to meet y'all earlier tonight!!! 💯

I'm excited to have sat down with a table of people who care about building healthy tech communities in Vancouver ⚡️💛⚡️

Can't wait to see what comes next, folks! 🚀

**Comment by AkimaLunar** [comment]
Here is the Spectrum chat for Vanjs: [https://spectrum.chat/vanjs](https://spectrum.chat/vanjs)

**Comment by apike** [comment]
I think this issue was a success – we now have a VanJS repo, Spectrum, and various other open source pieces like a code of conduct, speaking info, speaker issue template, goals, and so on. Thanks for kicking his off everybody, excited to see where you and other community members bring VanJS! 🎉

**Comment by Qard** [comment]
I think we can close this now. Feel free to reopen if you disagree.
